apiVersion: apps/v1
kind: Deployment
metadata:
  name: task5-nginx-deployment
  labels:
    app: task5-nginx
    task: task5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task5-nginx
  template:
    metadata:
      labels:
        app: task5-nginx
        task: task5
    spec:
      containers:
      - name: task5-nginx-container
        image: nginx:1.25.0
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

